[bell]
duration = 0

[colors.cursor]
cursor = "#f5e0dc"
text = "#1e1e2e"

[colors.footer_bar]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.hints.end]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.hints.start]
background = "#f9e2af"
foreground = "#1e1e2e"

[colors.normal]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[colors.primary]
background = "#1e1e2e"
bright_foreground = "#cdd6f4"
dim_foreground = "#7f849c"
foreground = "#cdd6f4"

[colors.search.focused_match]
background = "#a6e3a1"
foreground = "#1e1e2e"

[colors.search.matches]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.selection]
background = "#f5e0dc"
text = "#1e1e2e"

[colors.vi_mode_cursor]
cursor = "#b4befe"
text = "#1e1e2e"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[scrolling]
multiplier = 15

[window]
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = false
title = "🌿🌸🌺🌼🌱"

[window.padding]
x = 10
y = 10
