["track"]

"~" = [".tool-versions"]

"~/.config/" = [
  "bat",
  "eza",
  "ripgrep",
  "delta",
  "bottom",
  "tldr",
  "cosmic",
  "fish",
  "ghostty",
  "lazygit",
  "nvim",
  "wallpapers",
]

["run"]

"before" = []
"after" = []
