#! /bin/sh

# References:
# https://github.com/tsjazil/dotfiles

feh --bg-fill ~/.config/bspwm/wallpaper.jpg
# pgrep -x polybar >/dev/null || polybar &
~/.config/polybar/launch.sh
pgrep -x sxhkd >/dev/null || sxhkd &
# pgrep -x picom >/dev/null || picom &
pgrep -x dunst >/dev/null || dunst &

xrandr --output eDP --mode 2256x1504 &

# bspc monitor HDMI-1 -d I II III IV V
# bspc monitor eDP-1 -d VI VII VIII IX
bspc monitor eDP -d I II III IV V

# rosewater="#f5e0dc"
# flamingo="#f2cdcd"
# mauve="#cba6f7"
# pink="#f4bce1"
# red="#f28fad"
# maroon="#e0a3bf"
# peach="#f5c2e7"
# yellow="#f2e9de"
# green="#a6e3a1"
# teal="#94e2d5"
# sky="#89dceb"
# sapphire="#74c7ec"
blue="#89b4fa"
# lavender="#b4befe"
# text="#cdd6f4"
# subtext1="#bac2de"
# subtext0="#a6adc8"
# overlay2="#9399b2"
# overlay1="#7f849c"
overlay0="#6c7086"
# surface1="#45475a"
# surface0="#313244"
# base="#1e1e2e"
# mantle="#181825"
# crust="#11111b"

# Set the border colors.
bspc config normal_border_color "$overlay0"
bspc config active_border_color "$overlay0"
bspc config focused_border_color "$blue"
bspc config presel_feedback_color "$blue"

bspc config border_width 4.5
bspc config window_gap 9

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config bottom_padding 0
#bspc config top_padding 20
bspc config top_padding 40

# Remove x cursor
xsetroot -cursor_name left_ptr &

#Polybar Launching
# ~/.config/polybar/./launch.sh

# enable touchpad tapping and natural scrolling
xinput set-prop "PIXA3854:00 093A:0274 Touchpad" "libinput Tapping Enabled" 1
# xinput set-prop "PIXA3854:00 093A:0274 Touchpad" "libinput Tapping Drag Enabled"
# xinput set-prop "PIXA3854:00 093A:0274 Touchpad" "libinput Horizontal Scroll Enabled"
xinput set-prop "PIXA3854:00 093A:0274 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "PIXA3854:00 093A:0274 Touchpad" "libinput Middle Emulation Enabled" 1
