#!/bin/sh
# Autogenerated always sourced file - Fake bang path to help editors/linters

#
#  This is a list of known tmux versions, given in incremental order
#  So that once the running tmux is found, all comming before can be assumed
#  to be prior, ie features depending on such versions should work on the
#  current version
#
cache_known_tmux_vers="
0.0
0.8
0.9
1.0
1.1
1.2
1.3
1.4
1.5
1.6
1.7
1.8
1.9
1.9a
2.0
2.1
2.2
2.3
2.4
2.5
2.6
2.7
2.8
2.9
2.9a
3.0
3.0a
3.1
3.1a
3.1b
3.1c
3.2
3.2a
3.3
3.3a
3.4"

